CREATE DATABASE Forms
USE Forms

CREATE TABLE Signup_Form(
	firstname VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
)

--DROP TABLE Signup_Froms